
#include "BulletCollision/CollisionDispatch/SphereTriangleDetector.h"
#include "BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.h"
#include "BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.h"
#include "BulletCollision/CollisionDispatch/btBoxBoxDetector.h"
#include "BulletCollision/CollisionDispatch/btCollisionDispatcherMt.h"
#include "BulletCollision/CollisionDispatch/btCollisionWorldImporter.h"
#include "BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.h"
#include "BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.h"
#include "BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.h"
#include "BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.h"
#include "BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.h"
#include "BulletCollision/CollisionDispatch/btGhostObject.h"
#include "BulletCollision/CollisionDispatch/btInternalEdgeUtility.h"
#include "BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.h"
#include "BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.h"
#include "BulletCollision/CollisionShapes/btBox2dShape.h"
#include "BulletCollision/CollisionShapes/btConvex2dShape.h"
#include "BulletCollision/CollisionShapes/btConvexPointCloudShape.h"
#include "BulletCollision/CollisionShapes/btConvexPolyhedron.h"
#include "BulletCollision/CollisionShapes/btHeightfieldTerrainShape.h"
#include "BulletCollision/CollisionShapes/btMiniSDF.h"
#include "BulletCollision/CollisionShapes/btMinkowskiSumShape.h"
#include "BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.h"
#include "BulletCollision/CollisionShapes/btSdfCollisionShape.h"
#include "BulletCollision/CollisionShapes/btShapeHull.h"
#include "BulletCollision/CollisionShapes/btTriangleBuffer.h"
#include "BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.h"
#include "BulletCollision/Gimpact/btCompoundFromGimpact.h"
#include "BulletCollision/Gimpact/btContactProcessing.h"
#include "BulletCollision/Gimpact/btGImpactCollisionAlgorithm.h"
#include "BulletCollision/Gimpact/btGImpactMassUtil.h"
#include "BulletCollision/Gimpact/btGenericPoolAllocator.h"
#include "BulletCollision/Gimpact/gim_bitset.h"
#include "BulletCollision/Gimpact/gim_box_set.h"
#include "BulletCollision/Gimpact/gim_contact.h"
#include "BulletCollision/Gimpact/gim_hash_table.h"
#include "BulletCollision/NarrowPhaseCollision/btComputeGjkEpaPenetration.h"
#include "BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.h"
#include "BulletCollision/NarrowPhaseCollision/btGjkConvexCast.h"
#include "BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.h"
#include "BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.h"
#include "BulletCollision/NarrowPhaseCollision/btMprPenetration.h"
#include "BulletCollision/NarrowPhaseCollision/btPointCollector.h"
#include "BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.h"
#include "BulletDynamics/Character/btKinematicCharacterController.h"
#include "BulletDynamics/ConstraintSolver/btContactConstraint.h"
#include "BulletDynamics/ConstraintSolver/btNNCGConstraintSolver.h"
#include "BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolverMt.h"
#include "BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.h"
#include "BulletDynamics/Dynamics/btDiscreteDynamicsWorldMt.h"
#include "BulletDynamics/Featherstone/btMultiBodyConstraintSolver.h"
#include "BulletDynamics/Featherstone/btMultiBodyFixedConstraint.h"
#include "BulletDynamics/Featherstone/btMultiBodyGearConstraint.h"
#include "BulletDynamics/Featherstone/btMultiBodyJointFeedback.h"
#include "BulletDynamics/Featherstone/btMultiBodyJointLimitConstraint.h"
#include "BulletDynamics/Featherstone/btMultiBodyJointMotor.h"
#include "BulletDynamics/Featherstone/btMultiBodyLinkCollider.h"
#include "BulletDynamics/Featherstone/btMultiBodyPoint2Point.h"
#include "BulletDynamics/Featherstone/btMultiBodySliderConstraint.h"
#include "BulletDynamics/MLCPSolvers/btDantzigSolver.h"
#include "BulletDynamics/MLCPSolvers/btLemkeSolver.h"
#include "BulletDynamics/MLCPSolvers/btMLCPSolver.h"
#include "BulletDynamics/MLCPSolvers/btPATHSolver.h"
#include "BulletDynamics/MLCPSolvers/btSolveProjectedGaussSeidel.h"
#include "BulletSoftBody/btDefaultSoftBodySolver.h"
#include "BulletSoftBody/btSoftBodyConcaveCollisionAlgorithm.h"
#include "BulletSoftBody/btSoftBodyData.h"
#include "BulletSoftBody/btSoftBodyHelpers.h"
#include "BulletSoftBody/btSoftBodyInternals.h"
#include "BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.h"
#include "BulletSoftBody/btSoftMultiBodyDynamicsWorld.h"
#include "BulletSoftBody/btSoftRigidCollisionAlgorithm.h"
#include "BulletSoftBody/btSoftRigidDynamicsWorld.h"
#include "BulletSoftBody/btSoftSoftCollisionAlgorithm.h"
#include "LinearMath/btConvexHull.h"
#include "LinearMath/btConvexHullComputer.h"
#include "LinearMath/btCpuFeatureUtility.h"
#include "LinearMath/btGrahamScan2dConvexHull.h"
#include "LinearMath/btPoolAllocator.h"
#include "LinearMath/btStackAlloc.h"
#include "btBulletDynamicsCommon.h"

// NOTE: Bullet3 headers are disabled because Bindgen cannot generate code for the template partial specialization

// #include "Bullet3Collision/BroadPhaseCollision/b3DynamicBvhBroadphase.h"
// #include "Bullet3Collision/NarrowPhaseCollision/b3ConvexUtility.h"
// #include "Bullet3Collision/NarrowPhaseCollision/b3CpuNarrowPhase.h"
// #include "Bullet3Collision/NarrowPhaseCollision/b3RigidBodyCL.h"
// // #include "Bullet3Collision/NarrowPhaseCollision/shared/b3BvhTraversal.h"
// // #include "Bullet3Collision/NarrowPhaseCollision/shared/b3ClipFaces.h"
// // #include "Bullet3Collision/NarrowPhaseCollision/shared/b3ContactConvexConvexSAT.h"
// // #include "Bullet3Collision/NarrowPhaseCollision/shared/b3FindConcaveSatAxis.h"
// // #include "Bullet3Collision/NarrowPhaseCollision/shared/b3MprPenetration.h"
// // #include "Bullet3Collision/NarrowPhaseCollision/shared/b3NewContactReduction.h"
// // #include "Bullet3Collision/NarrowPhaseCollision/shared/b3UpdateAabbs.h"
// #include "Bullet3Common/b3FileUtils.h"
// #include "Bullet3Common/b3PoolAllocator.h"
// #include "Bullet3Common/b3Random.h"
// #include "Bullet3Common/b3ResizablePool.h"
// #include "Bullet3Dynamics/ConstraintSolver/b3FixedConstraint.h"
// #include "Bullet3Dynamics/ConstraintSolver/b3Generic6DofConstraint.h"
// #include "Bullet3Dynamics/ConstraintSolver/b3PgsJacobiSolver.h"
// #include "Bullet3Dynamics/ConstraintSolver/b3Point2PointConstraint.h"
// #include "Bullet3Dynamics/b3CpuRigidBodyPipeline.h"
// #include "Bullet3Dynamics/shared/b3ConvertConstraint4.h"
// #include "Bullet3Dynamics/shared/b3Inertia.h"
// #include "Bullet3Dynamics/shared/b3IntegrateTransforms.h"
// #include "Bullet3Geometry/b3ConvexHullComputer.h"
// #include "Bullet3Geometry/b3GeometryUtil.h"
// #include "Bullet3Geometry/b3GrahamScan2dConvexHull.h"
// #include "Bullet3OpenCL/BroadphaseCollision/b3GpuGridBroadphase.h"
// #include "Bullet3OpenCL/BroadphaseCollision/b3GpuParallelLinearBvhBroadphase.h"
// #include "Bullet3OpenCL/BroadphaseCollision/b3GpuSapBroadphase.h"
// #include "Bullet3OpenCL/NarrowphaseCollision/b3ContactCache.h"
// #include "Bullet3OpenCL/NarrowphaseCollision/b3ConvexHullContact.h"
// #include "Bullet3OpenCL/NarrowphaseCollision/b3ConvexPolyhedronCL.h"
// #include "Bullet3OpenCL/NarrowphaseCollision/b3GjkEpa.h"
// #include "Bullet3OpenCL/NarrowphaseCollision/b3SupportMappings.h"
// #include "Bullet3OpenCL/NarrowphaseCollision/b3TriangleIndexVertexArray.h"
// #include "Bullet3OpenCL/NarrowphaseCollision/b3VoronoiSimplexSolver.h"
// #include "Bullet3OpenCL/ParallelPrimitives/b3LauncherCL.h"
// #include "Bullet3OpenCL/ParallelPrimitives/b3PrefixScanFloat4CL.h"
// #include "Bullet3OpenCL/Raycast/b3GpuRaycast.h"
// #include "Bullet3OpenCL/RigidBody/b3GpuJacobiContactSolver.h"
// #include "Bullet3OpenCL/RigidBody/b3GpuNarrowPhase.h"
// #include "Bullet3OpenCL/RigidBody/b3GpuNarrowPhaseInternalData.h"
// #include "Bullet3OpenCL/RigidBody/b3GpuPgsConstraintSolver.h"
// #include "Bullet3OpenCL/RigidBody/b3GpuPgsContactSolver.h"
// #include "Bullet3OpenCL/RigidBody/b3GpuRigidBodyPipeline.h"
// #include "Bullet3OpenCL/RigidBody/b3GpuRigidBodyPipelineInternalData.h"
// #include "Bullet3OpenCL/RigidBody/b3Solver.h"
// #include "Bullet3Serialize/Bullet2FileLoader/b3BulletFile.h"
// #include "Bullet3Serialize/Bullet2FileLoader/b3DNA.h"
