[package]
name = "bullet-sys"
version = "0.1.1"
authors = ["Oleg Khryptul <okreptul@yahoo.com>"]
build = "build.rs"

[dependencies]

[build-dependencies]
cmake = "0.1.31"
bindgen = "0.36.1"

[features]
default = ["bind"]
build = []
bind = []
examples = []
tests = []
